allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smo-storage
provisioner: cluster.local/nfs-server-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
