apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustertemplates.o2ims.provisioning.oran.org
spec:
  group: o2ims.provisioning.oran.org
  names:
    kind: ClusterTemplate
    listKind: ClusterTemplateList
    plural: clustertemplates
    singular: clustertemplate
    shortNames:
      - ct
      - ctpl
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["name", "version"]
              properties:
                name:
                  type: string
                  description: "Human-readable name for this template"
                version:
                  type: string
                  description: "Template version (e.g., v1.0.0)"
                description:
                  type: string
                  description: "Description of what this template provides"
                provisioner:
                  type: string
                  description: "Cluster provisioner type"
                  default: "byoh"
                  enum: ["byoh", "docker", "aws", "gcp", "azure"]
                k8sVersions:
                  type: array
                  description: "Supported Kubernetes versions (v1.26.0 to v1.34.0)"
                  items:
                    type: string
                  default: ["v1.26.0", "v1.27.0", "v1.28.0", "v1.29.0", "v1.30.0", "v1.31.0", "v1.32.0", "v1.33.0", "v1.34.0"]
                defaultK8sVersion:
                  type: string
                  description: "Default Kubernetes version if not specified"
                  default: "v1.32.0"
                nodeRequirements:
                  type: object
                  description: "Node count requirements (minimum only, master count must be odd)"
                  properties:
                    minMasters:
                      type: integer
                      description: "Minimum number of master nodes (must be odd: 1, 3, 5, etc.)"
                      default: 1
                      minimum: 1
                    minWorkers:
                      type: integer
                      description: "Minimum number of worker nodes"
                      default: 0
                      minimum: 0
                networking:
                  type: object
                  description: "Networking configuration defaults"
                  properties:
                    podCidr:
                      type: string
                      default: "10.244.0.0/16"
                    serviceCidr:
                      type: string
                      default: "10.96.0.0/12"
                    cni:
                      type: string
                      default: "flannel"
                      enum: ["flannel", "calico", "cilium"]
                labels:
                  type: object
                  description: "Default labels to apply to clusters"
                  additionalProperties:
                    type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Active", "Deprecated", "Invalid"]
                  default: "Active"
                usageCount:
                  type: integer
                  description: "Number of clusters using this template"
                  default: 0
                lastUsed:
                  type: string
                  format: date-time
                  description: "Last time this template was used"
      additionalPrinterColumns:
        - name: Version
          type: string
          jsonPath: .spec.version
        - name: Default K8s
          type: string
          jsonPath: .spec.defaultK8sVersion
        - name: Min Masters
          type: integer
          jsonPath: .spec.nodeRequirements.minMasters
        - name: Min Workers
          type: integer
          jsonPath: .spec.nodeRequirements.minWorkers
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
