# ==========================================
# PLAY 1: Key Rotation & Inventory Setup
# ==========================================
- name: 1. Rotate Keys & Setup Inventory
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    input: "{{ lookup('file', 'input.json') | from_json }}"
    kubeconfig: "~/.kube/config"
  
  tasks:
    # ... (No changes needed in Play 1 tasks) ...
    # [Keep your existing Play 1 tasks here]
    - name: Delete old BootstrapKubeconfig objects
      shell: |
        kubectl --kubeconfig {{ kubeconfig }} delete bootstrapkubeconfig --all -n default --ignore-not-found=true

    - name: Get API Server Endpoint
      shell: |
        kubectl --kubeconfig {{ kubeconfig }} config view -ojsonpath='{.clusters[0].cluster.server}'
      register: api_server
    
    - name: Get CA Cert
      shell: |
        kubectl --kubeconfig {{ kubeconfig }} config view --flatten -ojsonpath='{.clusters[0].cluster.certificate-authority-data}'
      register: ca_cert

    - name: Create Fresh BootstrapKubeconfig
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: BootstrapKubeconfig
          metadata:
            name: "bootstrap-kubeconfig"
            namespace: default
          spec:
            apiserver: "{{ api_server.stdout }}"
            certificate-authority-data: "{{ ca_cert.stdout }}"
            token-ttl: 1h

    - name: Extract Token Data
      shell: |
        kubectl --kubeconfig {{ kubeconfig }} get bootstrapkubeconfig bootstrap-kubeconfig -n default -o=jsonpath='{.status.bootstrapKubeconfigData}'
      register: bootstrap_data
      until: bootstrap_data.stdout != ""
      retries: 10
      delay: 2

    - name: Save Token to File
      copy:
        content: "{{ bootstrap_data.stdout }}"
        dest: "./bootstrap-kubeconfig.conf"
        mode: '0600'

    - name: Add physical hosts to Ansible inventory
      add_host:
        name: "{{ item.host_ip }}"
        groups: physical_nodes
        ansible_user: "{{ item.host_user }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        byoh_hostname: "{{ item.host_name }}"
        byoh_id: "{{ item.host_id }}"
      loop: "{{ input.hosts }}"

# ==========================================
# PLAY 2: Host Provisioning (Physical Layer)
# ==========================================
- name: 2. Configure OS & Install Agent
  hosts: physical_nodes
  become: true
  vars:
    # 1. Load Input Data
    input: "{{ lookup('file', 'input.json') | from_json }}"
    
    # 2. Set Target Version from JSON (Default to 1.34.0 if missing)
    target_k8s_version: "{{ input.k8s_version | default('1.34.0') }}"
    
    # 3. Derive Package Version (e.g. 1.34.0-1.1)
    k8s_pkg_version: "{{ target_k8s_version }}-1.1"
    
    # 4. Derive Repo Version (e.g. v1.34)
    # Splits '1.34.0' -> ['1', '34', '0'] -> Takes first two parts
    k8s_repo_version: "v{{ target_k8s_version.split('.')[0] }}.{{ target_k8s_version.split('.')[1] }}"
    
    agent_binary: "./byoh-host-agent"
  
  tasks:
    # ... (OS Config tasks remain the same) ...
    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/swap/d' /etc/fstab

    - name: Load kernel modules
      shell: |
        modprobe overlay
        modprobe br_netfilter
        echo "overlay" > /etc/modules-load.d/containerd.conf
        echo "br_netfilter" >> /etc/modules-load.d/containerd.conf

    - name: Set sysctl params
      shell: |
        echo "net.bridge.bridge-nf-call-ip6tables = 1" > /etc/sysctl.d/kubernetes.conf
        echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/kubernetes.conf
        echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/kubernetes.conf
        sysctl --system

    - name: Install Containerd
      apt:
        name: containerd
        state: present
        update_cache: yes

    - name: Configure Containerd (SystemdCgroup Fix)
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
        systemctl restart containerd

    - name: Install K8s Prereqs
      apt:
        pkg: [apt-transport-https, ca-certificates, curl, gpg, socat, ebtables, ethtool, conntrack]
        state: present

    # UPDATED TASK: Uses the dynamic variables
    - name: Add K8s Repo & Install Binaries
      shell: |
        # Clean old repo to prevent conflicts
        rm -f /etc/apt/sources.list.d/kubernetes.list
        mkdir -p /etc/apt/keyrings
        
        # Add dynamic repo key
        curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ k8s_repo_version }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes
        
        # Add dynamic repo list
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_repo_version }}/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
        
        apt-get update
        # Install specific version with downgrade support
        apt-get install -y --allow-downgrades --allow-change-held-packages kubelet={{ k8s_pkg_version }} kubeadm={{ k8s_pkg_version }} kubectl={{ k8s_pkg_version }}
        apt-mark hold kubelet kubeadm kubectl

    - name: Upload Local Agent Binary
      copy:
        src: "{{ agent_binary }}"
        dest: /usr/local/bin/byoh-hostagent
        mode: '0755'
        force: yes

    - name: Copy Fresh Registration Key
      copy:
        src: ./bootstrap-kubeconfig.conf
        dest: /root/bootstrap-kubeconfig.conf

    - name: Start Agent
      shell: |
        pkill byoh-hostagent || true
        sleep 2
        nohup /usr/local/bin/byoh-hostagent --bootstrap-kubeconfig /root/bootstrap-kubeconfig.conf --skip-installation > /var/log/byoh.log 2>&1 &

# ==========================================
# PLAY 3: Cluster Orchestration (Logical Layer)
# ==========================================
- name: 3. Deploy Pinned Clusters
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    input: "{{ lookup('file', 'input.json') | from_json }}"
    kubeconfig: "~/.kube/config"
    
    # [UPDATED] Create the "vX.Y.Z" format required by the cluster template
    cluster_k8s_version: "v{{ input.k8s_version | default('1.34.0') }}"

  tasks:
    - name: Wait for ByoHosts to Register
      shell: |
        kubectl --kubeconfig {{ kubeconfig }} get byohost {{ item.host_name }} --no-headers -o custom-columns=":metadata.name"
      register: host_check
      until: host_check.stdout | trim == item.host_name
      retries: 60
      delay: 5
      ignore_errors: yes
      loop: "{{ input.hosts }}"

    - name: Remove Restrictive Webhook
      shell: |
        kubectl --kubeconfig {{ kubeconfig }} delete validatingwebhookconfiguration byoh-validating-webhook-configuration --ignore-not-found=true

    - name: Pin Hosts (Label ByoHosts with IDs)
      shell: |
        kubectl --kubeconfig {{ kubeconfig }} label byohost {{ item.host_name }} host-id={{ item.host_id }} --overwrite
      loop: "{{ input.hosts }}"

    - name: Generate and Apply Manifest
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition: "{{ lookup('template', 'templates/cluster.yaml.j2') }}"

    - name: Merge All Cluster Kubeconfigs
      shell: |
        echo "Starting Kubeconfig Merge..."
        mkdir -p ./tmp_kubeconfigs
        rm -f ./tmp_kubeconfigs/*
        
        SECRETS=""
        for i in {1..24}; do
            FOUND=$(kubectl --kubeconfig {{ kubeconfig }} get secrets --field-selector type=cluster.x-k8s.io/secret -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | grep -e '-kubeconfig$' || true)
            if [ -n "$FOUND" ]; then
                SECRETS="$FOUND"
                echo "Found secrets..."
                break
            fi
            echo "Waiting for secrets to appear... ($i/24)"
            sleep 5
        done

        if [ -z "$SECRETS" ]; then
            echo "ERROR: Timed out waiting for kubeconfig secrets!"
            exit 1
        fi

        KCONFIG_PATH_LIST=""
        for SEC in $SECRETS; do
            kubectl --kubeconfig {{ kubeconfig }} get secret $SEC -o jsonpath='{.data.value}' | base64 -d > "./tmp_kubeconfigs/${SEC}.conf"
            KCONFIG_PATH_LIST="./tmp_kubeconfigs/${SEC}.conf:${KCONFIG_PATH_LIST}"
        done
        KCONFIG_PATH_LIST=${KCONFIG_PATH_LIST%:}

        export KUBECONFIG="$KCONFIG_PATH_LIST"
        kubectl config view --flatten > ./all_clusters.kubeconfig
        rm -rf ./tmp_kubeconfigs
        echo "SUCCESS: Master kubeconfig saved to $(pwd)/all_clusters.kubeconfig"
      args:
        executable: /bin/bash
      register: merge_output

    - name: Display Merge Result
      debug:
        msg: "{{ merge_output.stdout_lines }}"